name: pages
on:
  push:
    branches:
    - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup locale
      run: |
        sudo locale-gen en_GB.UTF-8
        sudo update-locale
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        submodules: true
    - name: Checkout licsar-proc-test
      uses: actions/checkout@master
      with:
        repository: cemacrr/lics-proc-test
        path: licsar-proc-test
        fetch-depth: 0
        submodules: true
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: source
        requirements_path: .github/workflows/pages-requirements.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
